### ISSUE TITLE
Big button usage

### ISSUE THREAD

**Issue by davisi3** [runningstream/hugograyscale#3]
Hi! How to make this site to open in new tab?
{{< big-button text="Visit Download Page" href="https://github.com/runningstream/hugograyscale/" >}}

**Comment by runningstream** [comment]
You can edit "layouts/shortcodes/big-button.html" and add in `target="_blank"`.  Then that big-button shortcode would look like:

`<a href="{{ .Get "href" }}" target="_blank" class="btn btn-default btn-lg">{{ .Get "text" }}</a>`

The best way to do this is not to directly edit the "layouts/shortcodes/big-button.html" file directly in the themes directory though...  It's to make a shortcodes directory inside your site's layouts directory (not the theme's layouts directory), then copy "big-button.html" from the theme into your new site-specific shortcodes directory.  The one in your site layouts directory will override the one in the theme layouts directory.  That way - even if you update the theme some time you'll keep your copy of the shortcode separately.
