### ISSUE TITLE
Works great localy but not publicly

### ISSUE THREAD

**Issue by davisi3** [runningstream/hugograyscale#4]
Hi!
So, everything looks amazing and  works as expected when I view this site in localhost:1313 but when I connect to public IP it's just text. How so? I guess lot of things missing in /public

**Comment by runningstream** [comment]
Hrm - the demo site builds fine, and other sites build ok...

You say "when I connect to public IP" - do you mean the public IP of the box you're running Hugo on?  When Hugo is hosting the site as a demonstration (`hugo server`), you have to tell it what interface to bind to with `--bind`, the default is to listen only on localhost interface.  It sounds like you might be doing that already though.  You also have to tell hugo what the "baseURL" is - it calculates what addresses to use for page resources that way.  The same baseurl may not work for both localhost access and public IP-based address.

Gonna need some more debugging info on this if it's still a problem for you.  Something that would help - the site and command lines and hugo versions you're testing with.

**Comment by davisi3** [comment]
Hi! I've solved it shortly after I asked that question. You can close this.
I had to edit config file, "baseURL" as you wrote :)
